name: Portfolio Test CI

on:
  push:
    branches: [main]

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List project files
      run: ls -la

    # ✅ HTMLHint via npm
    - name: Install HTMLHint
      run: npm install -g htmlhint

    - name: Run HTMLHint
      run: htmlhint . --config .htmlhintrc

    # ✅ ESLint
    - name: Install ESLint
      run: npm install eslint --save-dev

    - name: Run ESLint
      run: npx eslint .

    - name: Echo success message
      run: echo "✅ GitHub Actions is working perfectly!"
